name: CVE to CPE Matcher

on:
  workflow_dispatch:
    inputs:
      cve_ids:
        description: 'Comma-separated CVE IDs (e.g., CVE-2024-1234,CVE-2023-0001)'
        required: true
        type: string
      output_format:
        description: 'Output format: json or csv (both are generated regardless)'
        required: false
        default: 'json'
        type: choice
        options: [json, csv]

jobs:
  match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run CVE→CPE matcher
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          python tools/cve_to_cpe.py "${{ github.event.inputs.cve_ids }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cve-to-cpe-results
          path: |
            cve_to_cpe.json
            cve_to_cpe.csv
